- name: deploy_postgres | CentOS | Install epel-release repo and pckges for success postgreSQL install
  ansible.builtin.yum:
    name: epel-release
    state: present
  tags:
    - basic-install
    - server-install
    
- name: deploy_postgres | CentOS | Add repository
  ansible.builtin.yum:
    name: http://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  tags:
    - basic-install
    - server-install

- name: deploy_postgres | CentOS | Install Postgres
  ansible.builtin.yum:
    name: 'postgresql{{ postgres_version }}-server'
    state: present
  tags:
    - basic-install 
    - server-install

- name: deploy_postgres | CentOS | initDB to success install
  ansible.builtin.shell: 'sudo /usr/pgsql-15/bin/postgresql-15-setup initdb'
  tags:
    - basic-install 
    - server-install

- name: deploy_postgres | CentOS | Postgres start and enable
  ansible.builtin.systemd_service:
    state: started
    name: 'postgresql-{{ postgres_version }}'
    enabled: true
  tags:
    - basic-install 
    - server-install